### ISSUE TITLE
gatsby 5

### ISSUE THREAD

**Issue by taivu** [audunru/gatsby-source-remote-file#85]
can we please update the dependency to the latest version of gatsby (v5)? thanks!

**Comment by audunru** [comment]
This should be fixed soon, I've just [released a beta](https://www.npmjs.com/package/gatsby-source-remote-file/v/0.6.1-beta.0) and will release a new version soon.

**Comment by sophia-eb** [comment]
@audunru It seems that this fix [commit](https://github.com/audunru/gatsby-source-remote-file/commit/1afde9ec788d0704b5eae944e41d79ea656ea65b) has not been released, could you make a release for it? Thank you!
![image](https://github.com/audunru/gatsby-source-remote-file/assets/39286439/5aa3b4b0-7d3d-4bfe-be61-ca7df40e8dc6)
